version: '3.8'
services:
  demonstration:
    image: obsidiandocker/obsidian
    restart: always
    container_name: obs-demonstration
    ports:
      - '3000:3000'
    volumes:
      - obsidian-volume:/usr/app
    environment:
      - REDIS_HOST=obs-redis
      - PG_USER=obsidian
      - PG_DATABASE=obsidian
      - PG_PORT=5432
      - PG_HOSTNAME=obs-postgres
      - PG_PASSWORD=lascaux
    depends_on:
      - postgres-server
      - redis-server
  postgres-server:
    image: obsidiandocker/postgres
    container_name: obs-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=lascaux
      - POSTGRES_USER=obsidian
      - POSTGRES_DATABASE=obsidian
      - POSTGRES_PORT=5432
      - POSTGRES_HOSTNAME=obs-postgres
    volumes:
      - postgres-volume:/usr/data/postgres
  redis-server:
    image: obsidiandocker/redis
    container_name: obs-redis
    ports:
      - '6379:6379'
    environment: 
      - REDIS_HOST=obs-redis
    volumes:
      - redis-volume:/usr/data/redis
volumes:
  redis-volume:
  postgres-volume:
  obsidian-volume: